"""initial schema

Revision ID: 639f7c41ec57
Revises: 
Create Date: 2026-04-14 07:16:25.567224
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '639f7c41ec57'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('strategy', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('profit_factor', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('trade_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hedge_fund_filings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(length=255), nullable=False),
    sa.Column('cik', sa.String(length=20), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=True),
    sa.Column('accession_number', sa.String(length=50), nullable=False),
    sa.Column('total_value', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index(op.f('ix_hedge_fund_filings_fund_name'), 'hedge_fund_filings', ['fund_name'], unique=False)
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('position_size', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('setup_type', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lessons', sa.Text(), nullable=True),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('macro_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('indicator', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('previous_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('GREEN', 'YELLOW', 'RED', name='macrostatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_macro_data_indicator'), 'macro_data', ['indicator'], unique=False)
    op.create_index('ix_macro_indicator_date', 'macro_data', ['indicator', 'date'], unique=True)
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sentiment', sa.Float(), nullable=True),
    sa.Column('related_symbols', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('trading_implication', sa.Text(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap', sa.Numeric(), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('hedge_fund_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filing_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('cusip', sa.String(length=9), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('shares', sa.Numeric(), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['filing_id'], ['hedge_fund_filings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hedge_fund_positions_symbol'), 'hedge_fund_positions', ['symbol'], unique=False)
    op.create_index('ix_hfp_filing_symbol', 'hedge_fund_positions', ['filing_id', 'symbol'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('ema_21', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('ema_200', sa.Float(), nullable=True),
    sa.Column('bb_upper', sa.Float(), nullable=True),
    sa.Column('bb_middle', sa.Float(), nullable=True),
    sa.Column('bb_lower', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('obv', sa.Numeric(), nullable=True),
    sa.Column('stoch_k', sa.Float(), nullable=True),
    sa.Column('stoch_d', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_indicators_ticker_date', 'indicators', ['ticker_id', 'date'], unique=True)
    op.create_table('ohlcv_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ohlcv_symbol_date', 'ohlcv_data', ['ticker_id', 'date'], unique=True)
    op.create_table('sentiment_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('news_sentiment', sa.Float(), nullable=True),
    sa.Column('reddit_sentiment', sa.Float(), nullable=True),
    sa.Column('reddit_mentions', sa.Integer(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('fear_greed_index', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sentiment_ticker_date', 'sentiment_scores', ['ticker_id', 'date'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('signal_type', sa.Enum('BUY', 'SELL', 'HOLD', 'AVOID', name='signaltype'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('position_size', sa.Float(), nullable=True),
    sa.Column('risk_rating', sa.Integer(), nullable=True),
    sa.Column('expected_hold_days', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('ta_score', sa.Float(), nullable=True),
    sa.Column('fundamental_score', sa.Float(), nullable=True),
    sa.Column('sentiment_score_val', sa.Float(), nullable=True),
    sa.Column('macro_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_signals_ticker_date', 'signals', ['ticker_id', 'date'], unique=False)
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('alert_price_above', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('alert_price_below', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_index('ix_signals_ticker_date', table_name='signals')
    op.drop_table('signals')
    op.drop_index('ix_sentiment_ticker_date', table_name='sentiment_scores')
    op.drop_table('sentiment_scores')
    op.drop_index('ix_ohlcv_symbol_date', table_name='ohlcv_data')
    op.drop_table('ohlcv_data')
    op.drop_index('ix_indicators_ticker_date', table_name='indicators')
    op.drop_table('indicators')
    op.drop_index('ix_hfp_filing_symbol', table_name='hedge_fund_positions')
    op.drop_index(op.f('ix_hedge_fund_positions_symbol'), table_name='hedge_fund_positions')
    op.drop_table('hedge_fund_positions')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_table('papers')
    op.drop_table('news_items')
    op.drop_index('ix_macro_indicator_date', table_name='macro_data')
    op.drop_index(op.f('ix_macro_data_indicator'), table_name='macro_data')
    op.drop_table('macro_data')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_hedge_fund_filings_fund_name'), table_name='hedge_fund_filings')
    op.drop_table('hedge_fund_filings')
    op.drop_table('backtest_results')
    # ### end Alembic commands ###
